### ISSUE TITLE
Custom URLs gets overwritten without warning

### ISSUE THREAD

**Issue by monizb** [xprilion/fireshort#4]
**Describe the bug**
When custom urls are same, the older link gets overwritten without warning

**To Reproduce**
1. Go to Admin Panel
2. Click on add buttton
3. Enter same custom URL as the one you already have
4. The new URL replaces the older URL

**Expected behavior**
If the provided custom URL already exists, show a warning before overwriting.

**Comment by ashuvssut** [comment]
I want to work on this issue. 
A javascript function will check if the current shorturl is  already existing on not.
I will create the warning dialog box which will ask the user if he wants to replace the existing one or try renaming again. 
Will submit PR within 5 days
