### ISSUE TITLE
Add auto short code generator, rather than always entering custom URLs

### ISSUE THREAD

**Issue by monizb** [xprilion/fireshort#5]
**Is your feature request related to a problem? Please describe.**
Whenever a new link needs to be created, A custom URL has to be added which is not ideal

**Describe the solution you'd like**
Whenever custom url is left empty auto-generate a non-colliding 5-10 character code as a custom url

**Comment by luckykumarirai** [comment]
Hello 
I would like to contribute to this issue.

**Comment by xprilion** [comment]
Great! Assigning to you @luckykumarirai. Do you think you can propose a plan of action here?
