### ISSUE TITLE
Speed up the redirect process

### ISSUE THREAD

**Issue by xprilion** [xprilion/fireshort#6]
**Is your feature request related to a problem? Please describe.**
The current redirect happens after the entire app is loaded, which is slow.

**Describe the solution you'd like**
The redirect should happen almost instantly.

**Describe alternatives you've considered**
It might be possible to split the app and have a specific page for the redirect.

**Comment by Siddhant-K-code** [comment]
Can You Please Explain it's implementation more? this looks interesting

**Comment by xprilion** [comment]
hey @Siddhant-K-code, the idea is to make the short links redirect faster than they currently do. The reason I see behind the slow performance is that I have missed out on code-splitting and that's causing the entire app's JS to load into the DOM before redirecting. If we could split out the redirect page as a separate component, we are likely to observe performance boost during redirect.

**Comment by ashuvssut** [comment]
I want to try this Code-Splitting work. 
Can you please assign me this issue?
will submit PR in 1 day

**Comment by xprilion** [comment]
@ashuvssut sounds good, please go ahead!
